#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'victor'
        hostname: ubuntu-pc
        username: victor
        password: '12345@'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - git
        - wget
    snaps:
        remove: true
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
