#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Dionatan Simioni'
        hostname: ubuntu-miner
        username: victor
        password: '12345@'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - gimp
        - git
        - wget
    snaps:
        - name: spotify
          channel: stable
          classic: false
    codecs:
        install: false
    drivers:
        install: false
    updates: all
    shutdown: reboot
